Output gemini.gif

Set Width 1920
Set Height 1080

Set PlaybackSpeed 1

Hide
Type "source .env"
Enter
Sleep 1s
Type " gemini extensions uninstall google-workspace-developer-tools"
Enter
Sleep 1s
Type "clear"
Enter
Sleep 1s
Show

Type "gemini extensions install https://github.com/googleworkspace/developer-tools"
Sleep 200ms
Enter
Sleep 2s
Type "Y"
Sleep 200ms
Enter
Sleep 2s

Type "gemini"
Sleep 200ms
Enter
Sleep 5s

Ctrl+t
Sleep 1s

Type "Tell me about Apps Script using the search_workspace_docs tool."
Sleep 200ms
Enter
Sleep 5s
Enter # Allow tool usage
Sleep 20s

Type "/quit"
Sleep 200ms
Enter
Sleep 3s
